"""Initial migration

Revision ID: 8869a73bc11c
Revises: 
Create Date: 2024-07-07 20:52:54.619398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8869a73bc11c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cablemodem',
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'provision', name='statusenum'), nullable=False),
    sa.Column('valid_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cablemodem')
    # ### end Alembic commands ###
